import{i as l,a as g,S as h}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const p=document.querySelector("input"),b=document.querySelector(".form"),d=()=>{const t=document.createElement("span");t.classList.add("loader"),document.body.append(t)},f=()=>{const t=document.querySelector(".loader");t&&t.remove()};let i=1;const m=15,u={apiKey:"42337135-3774c2f446ec3f71c1b4c916a",baseUrl:"https://pixabay.com/api/"};function L(t,o=1){return`${u.baseUrl}?key=${u.apiKey}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${m}`}async function y(){const t=p.value.trim(),o=L(t,i);try{const s=(await g.get(o)).data;w(s)}catch(a){console.error("Error fetching data:",a),f(),l.error({title:"Error",message:"An error occurred while fetching data. Please try again later.",position:"center"})}}b.addEventListener("submit",async function(t){if(t.preventDefault(),i=1,!p.value.trim()){l.error({title:"Error",message:"Please enter a valid search term"});return}d(),await y()});const c=document.querySelector(".btn-load");c.addEventListener("click",async function(){i++,d(),await y()});function w(t){const o=document.querySelector(".gallery"),a=new h(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),s=document.querySelector(".gallery-item");s&&(s.getBoundingClientRect().height,window.scrollBy(0,o.clientHeight));const e=t.hits.map(n=>`
        <li class="gallery-item">
            <a href="${n.largeImageURL}">
                <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}">
            </a>
            <p><b>Likes: </b>${n.likes}</p>
            <p><b>Views: </b>${n.views}</p>
            <p><b>Comments: </b>${n.comments}</p>
            <p><b>Downloads: </b>${n.downloads}</p>
        </li>`).join("");o.innerHTML+=e,a.refresh(),f(),(t.totalHits||0)<=i*m?(c.style.display="none",l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"center",transitionIn:"fadeInLeft"})):c.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
