import{S as h,i as s,a as b}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const f=document.querySelector("input"),L=document.querySelector(".form"),d=document.querySelector(".btn-load"),a=document.querySelector(".gallery");document.querySelector(".btn-load");let l=1;const m=15,p={apiKey:"42337135-3774c2f446ec3f71c1b4c916a",baseUrl:"https://pixabay.com/api/"},w=new h(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),y=()=>{const t=document.createElement("span");t.classList.add("loader"),document.body.append(t)},c=()=>{const t=document.querySelector(".loader");t&&t.remove()};function $(t,o=1){return`${p.baseUrl}?key=${p.apiKey}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${m}`}async function g(){const t=f.value.trim(),o=$(t,l);try{const r=await b.get(o);if(!r||!r.data||r.data.hits.length===0){s.info({title:"Info",message:"No images found for the given search term.",position:"center"}),a.innerHTML="",c();return}const i=r.data;v(i)}catch(r){console.error("Error fetching data:",r),c(),a.innerHTML="",r.response?s.error({title:"Error",message:`API Error: ${r.response.data.message}`,position:"center"}):r.request?s.error({title:"Error",message:"Network Error. Please check your internet connection.",position:"center"}):s.error({title:"Error",message:"An unexpected error occurred. Please try again later.",position:"center"})}}L.addEventListener("submit",async function(t){if(t.preventDefault(),l=1,!f.value.trim()){s.error({title:"Error",message:"Please enter a valid search term"});return}y(),await g(),t.target.reset(),c()});d.addEventListener("click",async function(){l++,y(),await g()});function v(t){const o=document.querySelector(".gallery-item");o&&(o.getBoundingClientRect().height,window.scrollBy(0,a.clientHeight));const r=t.hits.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p><b>Likes: </b>${e.likes}</p>
            <p><b>Views: </b>${e.views}</p>
            <p><b>Comments: </b>${e.comments}</p>
            <p><b>Downloads: </b>${e.downloads}</p>
        </li>`).join("");a.innerHTML+=r,w.refresh(),c(),(t.totalHits||0)<=l*m?(d.style.display="none",s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"center",transitionIn:"fadeInLeft"})):d.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
