import{S as h,i as n,a as b}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const e of o)if(e.type==="childList")for(const l of e.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(o){const e={};return o.integrity&&(e.integrity=o.integrity),o.referrerPolicy&&(e.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?e.credentials="include":o.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function c(o){if(o.ep)return;o.ep=!0;const e=s(o);fetch(o.href,e)}})();const L=document.querySelector("input"),w=document.querySelector(".form"),u=document.querySelector(".btn-load"),d=document.querySelector(".gallery");document.querySelector(".btn-load");let a=1;const m=15,f={apiKey:"42337135-3774c2f446ec3f71c1b4c916a",baseUrl:"https://pixabay.com/api/"},S=new h(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),y=()=>{const r=document.createElement("span");r.classList.add("loader"),document.body.append(r)},i=()=>{const r=document.querySelector(".loader");r&&r.remove()};function $(r,t=1){return`${f.baseUrl}?key=${f.apiKey}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${m}`}let p="";w.addEventListener("submit",async function(r){if(r.preventDefault(),a=1,p=L.value.trim(),!p){n.error({title:"Error",message:"Please enter a valid search term"});return}y(),await g(),r.target.reset(),i()});u.addEventListener("click",async function(){a++,y(),await g()});async function g(){const r=$(p,a);try{const t=await b.get(r);if(!t||!t.data||t.data.hits.length===0){n.info({title:"Info",message:"No images found for the given search term.",position:"center"}),i();return}const s=t.data;P(s)}catch(t){console.error("Error fetching data:",t),i(),d.innerHTML="",t.response?n.error({title:"Error",message:`API Error: ${t.response.data.message}`,position:"center"}):t.request?n.error({title:"Error",message:"Network Error. Please check your internet connection.",position:"center"}):n.error({title:"Error",message:"An unexpected error occurred. Please try again later.",position:"center"})}}function P(r){const t=document.querySelector(".gallery-item");t&&(t.getBoundingClientRect().height,window.scrollBy(0,d.clientHeight));const s=r.hits.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p><b>Likes: </b>${e.likes}</p>
            <p><b>Views: </b>${e.views}</p>
            <p><b>Comments: </b>${e.comments}</p>
            <p><b>Downloads: </b>${e.downloads}</p>
        </li>`).join("");d.innerHTML+=s,S.refresh(),i(),(r.totalHits||0)-a*m<=0?(u.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"center",transitionIn:"fadeInLeft"})):u.style.display="block"}
//# sourceMappingURL=commonHelpers.js.map
